# Generated by Django 3.2 on 2023-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='辩证论证id')),
                ('range', models.TextField(blank=True, max_length=300, verbose_name='适用范围')),
                ('type', models.CharField(blank=True, max_length=70, verbose_name='类型')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='临床表现')),
                ('bzimage', models.ImageField(blank=True, null=True, upload_to='article_img', verbose_name='辩证的图片')),
                ('recommend', models.TextField(blank=True, max_length=500, verbose_name='推荐处方')),
                ('prescription', models.TextField(blank=True, max_length=300, verbose_name='基础方剂')),
                ('take', models.TextField(blank=True, max_length=3000, verbose_name='服用方法')),
                ('medicine', models.TextField(blank=True, max_length=300, verbose_name='推荐中成药')),
                ('acupoint', models.TextField(blank=True, max_length=300, verbose_name='针灸穴位')),
                ('source', models.CharField(blank=True, max_length=70, verbose_name='出处')),
            ],
            options={
                'verbose_name': '辨证论治',
                'verbose_name_plural': '辨证论治',
            },
        ),
    ]
