# Generated by Django 3.2 on 2023-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_treatment_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='take',
            field=models.TextField(blank=True, max_length=3000, verbose_name='服用方法'),
        ),
    ]
